### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' in icinga2_version.py

### ISSUE THREAD

**Issue by jofiedler** [bodsch/ansible-icinga2#18]
##### SUMMARY

AttributeError: 'NoneType' object has no attribute 'group' in icinga2_version.py while running playbook for incina master installation.
Error in the current version. In version 1.2.2 this error does not occur
##### STEPS TO REPRODUCE

```- hosts: icinga2_server
  gather_facts: true
  become: true
  roles:

    - role: monitoring-plugins-role
    - role: mariadb-role

    - role: icinga2-role
      tags: icinga2-role-server

    - role: nginx-role
    - role: php-role
    - role: icingaweb2-role
  tags: icinga-master

```

##### EXPECTED RESULTS

```paste below

```

##### ACTUAL RESULTS

```paste below

```

##### ENVIRONMENT

icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.3)

**Comment by bodsch** [comment]
Could I get a snippet of the Ansible log?
Which OS is used?
Which Icinga2 version should be installed?
Which python version is used on the target system?

**Comment by bodsch** [comment]
different version strings between different operationsystems:
- debian: `version: r2.12.3-1`
- redhat: `version: 2.12.3`

**Comment by jofiedler** [comment]
> 
> 
> Could I get a snippet of the Ansible log?
> Which OS is used?
>> Oracle Linux 8
> Which Icinga2 version should be installed?
>> 2.12.3
> Which python version is used on the target system?
>> Python 3.6.8
