### ISSUE TITLE
ansible_ssh_user is deprecated since ansible 2.0

### ISSUE THREAD

**Issue by jtognazzi** [bodsch/ansible-icinga2#24]
the variable ansible_ssh_user is undefined when I run the icinga2 role.

I think it would be better to use ansible_user_id

for example here:
https://github.com/bodsch/ansible-icinga2/blob/4b3208b6d07bfb7aa685a1af78b4d594b33f2a7a/tasks/satellite/pki.yml#L23

**Comment by bodsch** [comment]
Hi @jtognazzi!
Thanks for your feedback! I will test this ASAP
